#!/usr/bin/env python3
"""AstroNews Telegram bot — interactive watchlist management.

Long-running service: long-polls Telegram getUpdates, dispatches commands,
mutates the SQLite DB and rewrites topics.md (union of all users' active
topics) so the cloud routine picks up changes on its next fire.

Commands:
    /start            register the user, show welcome
    /watchlist        show current topics with numbers
    /add <topic>      add a topic (rejects at the per-user cap)
    /remove <n|text>  remove by number or exact text
    /help             list commands

Reads ~/.config/astronews/credentials.env for TELEGRAM_BOT_TOKEN.
The chat_id config var is unused here — bot accepts any chat that messages it.
"""

from __future__ import annotations

import contextlib
import fcntl
import json
import os
import signal
import subprocess
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

# Make sibling modules importable even when run directly.
sys.path.insert(0, str(Path(__file__).resolve().parent))
import db as dbm  # noqa: E402
import classify as classifier  # noqa: E402

# Lazily-initialised Anthropic client. Allowed to fail at startup — synchronous
# /add classification then degrades to "Added" without atom info, and the
# 15-min systemd timer picks the topic up later.
_anthropic_client = None
_anthropic_client_error: str | None = None


def get_anthropic_client():
    global _anthropic_client, _anthropic_client_error
    if _anthropic_client is not None:
        return _anthropic_client
    if _anthropic_client_error is not None:
        return None
    try:
        _anthropic_client = classifier.get_client()
        return _anthropic_client
    except Exception as e:  # noqa: BLE001
        _anthropic_client_error = f"{type(e).__name__}: {e}"
        print(f"anthropic client init failed: {_anthropic_client_error}", file=sys.stderr)
        return None


def classify_inline(conn, chat_id: int, topic: str) -> dict | None:
    """Classify a topic synchronously. Returns the result dict on success,
    None on any failure (caller should fall back to a generic message)."""
    client = get_anthropic_client()
    if client is None:
        return None
    try:
        return classifier.classify_and_persist(conn, client, chat_id, topic)
    except Exception as e:  # noqa: BLE001
        print(f"inline classify failed for {chat_id}/{topic!r}: "
              f"{type(e).__name__}: {e}", file=sys.stderr)
        return None


def fmt_atoms_inline(info: dict) -> str:
    """Render the classify result as a short suffix for the bot reply."""
    parts = []
    if info["include"]:
        parts.append("+ " + ", ".join(info["include"]))
    if info["exclude"]:
        parts.append("− " + ", ".join(info["exclude"]))
    tail = ""
    if info["new_atoms"]:
        tail = f" <i>(new: {', '.join(info['new_atoms'])})</i>"
    return ("  <i>(" + " | ".join(parts) + ")</i>" + tail) if parts else ""

REPO_ROOT = Path(__file__).resolve().parent.parent
TOPICS_FILE = REPO_ROOT / "topics.md"
LOCK_FILE = Path(os.path.expanduser("~/.astronews.lock"))
CREDENTIALS_FILE = Path(os.path.expanduser("~/.config/astronews/credentials.env"))

TELEGRAM_API = "https://api.telegram.org/bot{token}/{method}"
LONG_POLL_TIMEOUT = 25     # seconds
MAX_TOPICS_PER_USER = 5
TOPIC_MAX_CHARS = 120
DEFAULT_TOPICS = ["stablecoins"]   # auto-added to a user's watchlist on first /start
N_SUGGESTED_TOPICS = 3             # how many popular topics to suggest in /start
ADMIN_CHAT_IDS = {655916874}       # chat_ids allowed to run /admin commands
TOPICS_HEADER = """\
# Topics — auto-managed by the bot.
# This file is the UNION of every user's active topic list.
# Edit topics from Telegram via /add and /remove (do not edit this file by hand).
"""

_running = True


def _stop(*_):
    global _running
    _running = False


signal.signal(signal.SIGTERM, _stop)
signal.signal(signal.SIGINT, _stop)


# --- credentials ----------------------------------------------------------

def load_token() -> str:
    if not CREDENTIALS_FILE.exists():
        sys.exit(f"missing credentials at {CREDENTIALS_FILE}")
    for raw in CREDENTIALS_FILE.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        if k.strip() == "TELEGRAM_BOT_TOKEN":
            return v.strip().strip('"').strip("'")
    sys.exit("TELEGRAM_BOT_TOKEN missing from credentials")


# --- telegram api ---------------------------------------------------------

def tg_call(token: str, method: str, params: dict, timeout: int = 30) -> dict:
    url = TELEGRAM_API.format(token=token, method=method)
    data = urllib.parse.urlencode(params).encode()
    req = urllib.request.Request(url, data=data)
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read())


def send(token: str, chat_id: int, text: str, parse_mode: str = "HTML") -> dict:
    return tg_call(token, "sendMessage", {
        "chat_id": chat_id,
        "text": text,
        "parse_mode": parse_mode,
        "disable_web_page_preview": "true",
    })


# --- topics.md sync -------------------------------------------------------

def rewrite_topics_md(conn) -> bool:
    """Rewrite topics.md as the alphabetised union of every user's topics.
    Returns True if the file content changed."""
    topics = dbm.all_active_topics(conn)
    body = TOPICS_HEADER + "\n" + "\n".join(topics) + ("\n" if topics else "")
    if TOPICS_FILE.exists() and TOPICS_FILE.read_text() == body:
        return False
    TOPICS_FILE.parent.mkdir(parents=True, exist_ok=True)
    TOPICS_FILE.write_text(body)
    return True


@contextlib.contextmanager
def repo_lock():
    """Hold the shared flock used by scrape + notify so concurrent git/DB
    ops serialize across all three services."""
    LOCK_FILE.touch(exist_ok=True)
    f = open(LOCK_FILE, "r+")
    try:
        fcntl.flock(f.fileno(), fcntl.LOCK_EX)
        yield
    finally:
        fcntl.flock(f.fileno(), fcntl.LOCK_UN)
        f.close()


def git(*args: str) -> tuple[int, str, str]:
    res = subprocess.run(
        ["git", *args], cwd=REPO_ROOT, capture_output=True, text=True,
    )
    return res.returncode, res.stdout.strip(), res.stderr.strip()


def commit_and_push(message: str) -> tuple[bool, str]:
    """Stage state/ + topics.md, commit if there are diffs, push (with retry).

    Caller is responsible for holding the repo_lock — this function does not
    acquire it.
    """
    code, _, err = git("add", "state/", "topics.md")
    if code != 0:
        return False, f"git add failed: {err}"
    # Only commit if something is actually staged.
    code, _, _ = git("diff", "--cached", "--quiet")
    if code == 0:
        return True, "no diffs to commit"
    code, _, err = git(
        "-c", "user.name=AstroNews Bot",
        "-c", "user.email=astronews-bot@noreply.local",
        "commit", "-m", message,
    )
    if code != 0:
        return False, f"git commit failed: {err}"
    # Push, with one pull-rebase retry on race.
    for _ in range(2):
        code, _, err = git("push", "origin", "main")
        if code == 0:
            return True, f"pushed: {message}"
        git("pull", "--rebase", "--quiet", "origin", "main")
    return False, f"git push failed after retry: {err}"


# --- command handlers -----------------------------------------------------

def fmt_watchlist(conn, chat_id: int, topics: list[str], verbose: bool = False) -> str:
    if not topics:
        return (
            "<b>Your watchlist is empty.</b>\n\n"
            "Add a topic with <code>/add &lt;topic&gt;</code>.\n"
            f"You can follow up to {MAX_TOPICS_PER_USER} topics."
        )
    lines = [f"<b>Your watchlist</b> ({len(topics)}/{MAX_TOPICS_PER_USER}):"]
    for i, t in enumerate(topics, 1):
        if verbose:
            inc, exc = dbm.get_facets(conn, chat_id, t)
            tags_parts = []
            if inc:
                tags_parts.append("+ " + ", ".join(inc))
            if exc:
                tags_parts.append("− " + ", ".join(exc))
            tags = "  <i>(" + " | ".join(tags_parts) + ")</i>" if tags_parts else "  <i>(unclassified)</i>"
            lines.append(f"{i}. {t}{tags}")
        else:
            lines.append(f"{i}. {t}")
    lines += [
        "",
        "<code>/add &lt;topic&gt;</code> to add",
        "<code>/remove &lt;n|text&gt;</code> to remove",
        "<code>/retag &lt;n&gt;</code> to re-classify a topic",
        "<code>/watchlist verbose</code> to see atom tags",
    ]
    return "\n".join(lines)


HELP_TEXT = (
    "<b>AstroNews bot — commands</b>\n"
    "<b>Topics:</b>\n"
    "/watchlist — your topics  (<code>/watchlist verbose</code> shows atom tags)\n"
    "/add &lt;topic&gt; — add a topic\n"
    "/remove &lt;n|text&gt; — remove by number or text\n"
    "/retag &lt;n&gt; — re-classify a topic\n"
    "<b>Sources:</b>\n"
    "/sources — your watched URLs\n"
    "/addsource &lt;url&gt; [→ &lt;topic&gt;] — watch a URL, optionally route under a topic\n"
    "/removesource &lt;n|url&gt; — unwatch\n"
    "<b>Other:</b>\n"
    "/help — this message\n\n"
    f"Caps: {MAX_TOPICS_PER_USER} topics, {dbm.MAX_SOURCES_PER_USER} sources per user.\n"
    "You'll receive a digest every 6 hours."
)


def fmt_sources(sources: list, max_cap: int) -> str:
    if not sources:
        return (
            "<b>No watched sources yet.</b>\n\n"
            "Add a URL with <code>/addsource &lt;url&gt;</code> "
            "or <code>/addsource &lt;url&gt; → &lt;topic&gt;</code> to route under one of your topics."
        )
    lines = [f"<b>Watched sources</b> ({len(sources)}/{max_cap}):"]
    for i, s in enumerate(sources, 1):
        topic = s["topic"] or "—"
        lines.append(f"{i}. {s['source_url']}\n    <i>routes to:</i> {topic}")
    lines += [
        "",
        "<code>/addsource &lt;url&gt; [→ &lt;topic&gt;]</code> to add",
        "<code>/removesource &lt;n|url&gt;</code> to remove",
    ]
    return "\n".join(lines)


def parse_addsource_arg(arg: str) -> tuple[str | None, str | None]:
    """Split `<url> [→ <topic>]` (also accepts `->`). Returns (url, topic|None)."""
    arg = arg.strip()
    for sep in ("→", "->"):
        if sep in arg:
            url_part, topic = arg.split(sep, 1)
            return url_part.strip(), topic.strip() or None
    return arg or None, None


def handle_command(token: str, conn, chat_id: int, username: str | None,
                   first_name: str | None, text: str) -> None:
    text = text.strip()
    parts = text.split(maxsplit=1)
    cmd = parts[0].lower()
    arg = parts[1].strip() if len(parts) > 1 else ""

    # Strip optional bot-mention suffix like /watchlist@MyBot
    if "@" in cmd:
        cmd = cmd.split("@", 1)[0]

    is_new = dbm.upsert_user(conn, chat_id, username, first_name)
    state_changed = False

    if cmd in ("/start", "/help"):
        if cmd == "/start":
            # New users get a default starter topic so their first digest isn't empty.
            if is_new:
                state_changed = True
                for default in DEFAULT_TOPICS:
                    if dbm.add_topic(conn, chat_id, default):
                        pass  # event logged inside add_topic
            current = dbm.get_topics(conn, chat_id)
            suggested = [
                t for t, _ in dbm.top_topics(conn, N_SUGGESTED_TOPICS + len(current))
                if t not in current
            ][:N_SUGGESTED_TOPICS]
            parts = ["<b>Welcome to AstroNews.</b>",
                     "I send a curated 6-hourly news digest based on topics you follow."]
            if current:
                parts.append("")
                parts.append(f"<b>Your watchlist</b> ({len(current)}/{MAX_TOPICS_PER_USER}):")
                parts.extend(f"• {t}" for t in current)
            if suggested:
                parts.append("")
                parts.append("<b>Popular topics you might add:</b>")
                parts.extend(f"• {s}" for s in suggested)
                parts.append("Add any with <code>/add &lt;topic&gt;</code>.")
            parts.append("")
            parts.append(HELP_TEXT)
            send(token, chat_id, "\n".join(parts))
        else:
            send(token, chat_id, HELP_TEXT)

    elif cmd == "/watchlist":
        verbose = arg.lower() in ("verbose", "v", "tags", "detail")
        topics = dbm.get_topics(conn, chat_id)
        send(token, chat_id, fmt_watchlist(conn, chat_id, topics, verbose=verbose))

    elif cmd == "/add":
        if not arg:
            send(token, chat_id, "Usage: <code>/add &lt;topic&gt;</code>")
            return
        if len(arg) > TOPIC_MAX_CHARS:
            send(token, chat_id, f"Topic too long (max {TOPIC_MAX_CHARS} chars).")
            return
        current = dbm.get_topics(conn, chat_id)
        if len(current) >= MAX_TOPICS_PER_USER:
            send(token, chat_id,
                 f"You're at the {MAX_TOPICS_PER_USER}-topic cap. "
                 "Remove one first with /remove.")
            return
        if any(arg.lower() == t.lower() for t in current):
            send(token, chat_id, f"You already follow <i>{arg}</i>.")
            return
        if dbm.add_topic(conn, chat_id, arg):
            state_changed = True
            dbm.refresh_user_label(conn, chat_id, username, first_name)
            info = classify_inline(conn, chat_id, arg)
            atom_suffix = fmt_atoms_inline(info) if info else ""
            send(token, chat_id,
                 f"Added <i>{arg}</i>. You now follow {len(current)+1} topic(s).{atom_suffix}")

    elif cmd == "/remove":
        if not arg:
            send(token, chat_id,
                 "Usage: <code>/remove &lt;number&gt;</code> or <code>/remove &lt;text&gt;</code>")
            return
        current = dbm.get_topics(conn, chat_id)
        target = None
        if arg.isdigit():
            idx = int(arg) - 1
            if 0 <= idx < len(current):
                target = current[idx]
        if target is None:
            for t in current:
                if t.lower() == arg.lower():
                    target = t
                    break
        if target is None:
            send(token, chat_id,
                 f"Couldn't find a matching topic. Run /watchlist to see your list.")
            return
        if dbm.remove_topic(conn, chat_id, target):
            state_changed = True
            dbm.refresh_user_label(conn, chat_id, username, first_name)
            send(token, chat_id, f"Removed <i>{target}</i>.")

    elif cmd == "/retag":
        if not arg:
            send(token, chat_id,
                 "Usage: <code>/retag &lt;number&gt;</code> "
                 "(use /watchlist to see numbers).")
            return
        current = dbm.get_topics(conn, chat_id)
        target = None
        if arg.isdigit():
            idx = int(arg) - 1
            if 0 <= idx < len(current):
                target = current[idx]
        if target is None:
            for t in current:
                if t.lower() == arg.lower():
                    target = t
                    break
        if target is None:
            send(token, chat_id, "Couldn't find a matching topic.")
            return
        if dbm.mark_unclassified(conn, chat_id, target):
            state_changed = True
            dbm.refresh_user_label(conn, chat_id, username, first_name)
            info = classify_inline(conn, chat_id, target)
            atom_suffix = fmt_atoms_inline(info) if info else ""
            if info:
                send(token, chat_id, f"Re-classified <i>{target}</i>.{atom_suffix}")
            else:
                send(token, chat_id,
                     f"Cleared classification for <i>{target}</i>. "
                     "Will re-classify on the next 15-min cycle.")

    elif cmd == "/sources":
        sources = list(dbm.get_user_sources(conn, chat_id))
        send(token, chat_id, fmt_sources(sources, dbm.MAX_SOURCES_PER_USER))

    elif cmd == "/addsource":
        if not arg:
            send(token, chat_id,
                 "Usage: <code>/addsource &lt;url&gt; [→ &lt;topic&gt;]</code>")
            return
        url, route_topic = parse_addsource_arg(arg)
        if not url or not (url.startswith("http://") or url.startswith("https://")):
            send(token, chat_id, "URL must start with http:// or https://")
            return
        current = list(dbm.get_user_sources(conn, chat_id))
        if len(current) >= dbm.MAX_SOURCES_PER_USER:
            send(token, chat_id,
                 f"You're at the {dbm.MAX_SOURCES_PER_USER}-source cap. "
                 "Remove one with /removesource first.")
            return
        # If route_topic is supplied, warn-but-accept if it isn't in user's watchlist
        if route_topic:
            user_topics = dbm.get_topics(conn, chat_id)
            if not any(route_topic.lower() == t.lower() for t in user_topics):
                send(token, chat_id,
                     f"<i>Note:</i> &lt;{route_topic}&gt; isn't in your /watchlist. "
                     "Posts will go under <i>Watched sources</i> until you /add it.")
        if dbm.add_user_source(conn, chat_id, url, route_topic):
            state_changed = True
            dbm.refresh_user_label(conn, chat_id, username, first_name)
            tail = f" routed under <i>{route_topic}</i>" if route_topic else ""
            send(token, chat_id,
                 f"Watching <code>{url}</code>{tail}. Scraper picks it up within 30 min.")
        else:
            send(token, chat_id, f"You're already watching that URL.")

    elif cmd == "/removesource":
        if not arg:
            send(token, chat_id,
                 "Usage: <code>/removesource &lt;number&gt;</code> "
                 "or <code>/removesource &lt;url&gt;</code>")
            return
        current = list(dbm.get_user_sources(conn, chat_id))
        target = None
        if arg.isdigit():
            idx = int(arg) - 1
            if 0 <= idx < len(current):
                target = current[idx]["source_url"]
        if target is None:
            for s in current:
                if s["source_url"].lower() == arg.lower():
                    target = s["source_url"]
                    break
        if target is None:
            send(token, chat_id, "Couldn't find a matching source.")
            return
        if dbm.remove_user_source(conn, chat_id, target):
            state_changed = True
            dbm.refresh_user_label(conn, chat_id, username, first_name)
            send(token, chat_id, f"Stopped watching <code>{target}</code>.")

    elif cmd == "/admin":
        if chat_id not in ADMIN_CHAT_IDS:
            send(token, chat_id, "Admin commands are restricted.")
            return
        sub_parts = arg.split(maxsplit=2) if arg else []
        sub = sub_parts[0].lower() if sub_parts else ""
        if sub == "atoms":
            atoms = dbm.all_atoms(conn)
            if not atoms:
                send(token, chat_id, "<i>No atoms yet.</i>")
                return
            lines = [f"<b>Atoms</b> ({len(atoms)}):"]
            for a in atoms:
                seed = " 🌱" if a["is_seed"] else ""
                lines.append(f"• <code>{a['atom_id']}</code> [{a['kind']}]{seed}\n  {a['description']}")
            send(token, chat_id, "\n".join(lines))
        elif sub == "merge" and len(sub_parts) >= 3:
            keep, drop = sub_parts[1].strip(), sub_parts[2].strip()
            try:
                n = dbm.merge_atoms(conn, keep, drop)
                state_changed = True
                send(token, chat_id,
                     f"Merged <code>{drop}</code> → <code>{keep}</code> "
                     f"({n} facet rows updated, atom <code>{drop}</code> deleted).")
            except ValueError as e:  # noqa: BLE001
                send(token, chat_id, f"Error: {e}")
        else:
            send(token, chat_id,
                 "<b>Admin commands</b>\n"
                 "/admin atoms — list all atoms\n"
                 "/admin merge &lt;keep_id&gt; &lt;drop_id&gt; — merge two atoms")

    else:
        # Non-command messages: gentle nudge
        send(token, chat_id, "Unknown command. Send /help to see what I can do.")
        return

    if state_changed:
        rewrite_topics_md(conn)
        ok, info = commit_and_push(
            f"bot: {username or chat_id} {cmd} {arg}".strip()
        )
        if not ok:
            print(f"git sync error: {info}", file=sys.stderr)


# --- update loop ----------------------------------------------------------

def process_update(token: str, update: dict) -> int | None:
    """Process one Telegram update. Acquires the repo_lock for the whole
    duration so DB writes + git ops are atomic vs. scrape and notify.

    Returns the update_id (so the caller can advance the long-poll offset).
    """
    update_id = update.get("update_id")
    msg = update.get("message") or update.get("edited_message") or {}
    chat = msg.get("chat") or {}
    chat_id = chat.get("id")
    text = msg.get("text") or ""
    if not chat_id or not text.startswith("/"):
        return update_id
    user = msg.get("from") or {}
    username = user.get("username")
    first_name = user.get("first_name")
    try:
        with repo_lock():
            conn = dbm.connect()
            dbm.init_schema(conn)
            try:
                handle_command(token, conn, chat_id, username, first_name, text)
            finally:
                conn.close()
    except Exception as e:  # noqa: BLE001
        print(f"handler error for chat {chat_id}: {type(e).__name__}: {e}",
              file=sys.stderr)
        try:
            send(token, chat_id,
                 "Sorry — something went wrong handling that command.")
        except Exception:  # noqa: BLE001
            pass
    return update_id


def main() -> int:
    token = load_token()
    # Touch the DB once at startup so the schema is initialised before any update
    # arrives. Also seeds state/ if empty.
    with repo_lock():
        conn = dbm.connect()
        dbm.init_schema(conn)
        conn.close()

    offset_file = REPO_ROOT / "state" / "bot_offset.txt"
    last_id = 0
    if offset_file.exists():
        try:
            last_id = int(offset_file.read_text().strip())
        except Exception:
            last_id = 0
    print(f"bot starting; offset={last_id}")

    while _running:
        try:
            resp = tg_call(token, "getUpdates", {
                "offset": last_id + 1 if last_id else 0,
                "timeout": LONG_POLL_TIMEOUT,
                "allowed_updates": json.dumps(["message", "edited_message"]),
            }, timeout=LONG_POLL_TIMEOUT + 5)
        except Exception as e:  # noqa: BLE001
            print(f"getUpdates error: {type(e).__name__}: {e}", file=sys.stderr)
            time.sleep(5)
            continue
        if not resp.get("ok"):
            print(f"getUpdates not ok: {resp}", file=sys.stderr)
            time.sleep(5)
            continue
        for update in resp.get("result", []):
            update_id = process_update(token, update)
            if update_id is not None:
                last_id = update_id
                offset_file.parent.mkdir(parents=True, exist_ok=True)
                offset_file.write_text(str(last_id) + "\n")

    print("bot stopped cleanly")
    return 0


if __name__ == "__main__":
    sys.exit(main())
